name: Collect Artist Analytics Data

on:
  schedule:
    # Run daily at 2:30 AM UTC (adjusted for your timezone)
    - cron: '30 2 * * *'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write  # Need write permission to commit data files

jobs:
  collect-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper git operations

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r BOMB/scripts/requirements.txt

      - name: Run data collection script
        env:
          WORKER_API_URL: ${{ secrets.WORKER_API_URL || 'https://casa24-api.casa24records.workers.dev' }}
          WORKER_API_KEY: ${{ secrets.WORKER_API_KEY || '' }}
        run: |
          cd BOMB/scripts
          python collect_data.py

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code BOMB/data/ || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add BOMB/data/
          git commit -m "Update analytics data - $(date +'%Y-%m-%d')"
          git push

      - name: Create issue on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Data Collection Failed - ' + new Date().toISOString().split('T')[0],
              body: 'The automated data collection workflow failed. Please check the logs: ' + context.payload.repository.html_url + '/actions/runs/' + context.runId,
              labels: ['automated', 'data-collection', 'bug']
            })
